version: '2'
services:
  minion:
    image: indigo/docker-minion
    env_file:
      - .minion.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "18980:18980"
      - "162:162/udp"
      - "514:514/udp"
