version: 2.0

defaults: &defaults

  working_directory: /home/circleci/minion

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

references:
  container_config: &container_config
    docker:
      - image: docker:17.11.0-ce-git

  dockerhub_login: &dockerhub_login
    run:
      name: DockerHub Login
      command: |
        docker login -u ${dockerhub_login} -p ${dockerhub_pass}

jobs:
  build_docker_image:
    <<: *defaults
    <<: *container_config

    steps:
      - setup_remote_docker
      - *attach_workspace
      - checkout
      - run:
          name: Generate version number for Docker tag
          command: |
            DOCKERHUB_TAG=${CIRCLE_BRANCH#release/}
            DOCKERHUB_TAG=${DOCKERHUB_TAG/\//-}
            echo ${DOCKERHUB_TAG} > /tmp/workspace/dockertag
      - run:
          name: Build Minion Docker Image
          command: |
            docker build -t opennms/minion:$(cat /tmp/workspace/dockertag) .
      - run:
          name: Save Docker Container Image as artifact in workspace
          command: |
            docker image save opennms/minion:$(cat /tmp/workspace/dockertag) -o /tmp/workspace/minion-docker-image
      - store_artifacts:
          path: /tmp/workspace/minion-docker-image
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - minion-docker-image
            - dockertag

  publish_dockerhub:
    <<: *defaults
    <<: *container_config

    steps:
      - setup_remote_docker
      - *attach_workspace
      - *dockerhub_login
      - run:
          name: Load Docker Container Image file
          command: |
            docker image load -i /tmp/workspace/minion-docker-image
      - run:
          name: Tag Docker Container Images
          command: |
            case "${CIRCLE_BRANCH}" in
              master)
                docker tag opennms/minion:$(cat /tmp/workspace/dockertag) opennms/minion:bleeding
                docker push opennms/minion:bleeding
                ;;
              drift)
                docker tag opennms/minion:$(cat /tmp/workspace/dockertag) opennms/minion:drift
                docker push opennms/minion:drift
                ;;
              release*)
                docker tag opennms/minion:$(cat /tmp/workspace/dockertag) opennms/minion:latest
                docker push opennms/minion:latest
                docker push opennms/minion:$(cat /tmp/workspace/dockertag)
                ;;
              *)
                echo "This is not a branch build which needs to be published"
                ;;
            esac

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker_image
      - publish_dockerhub:
          filters:
            branches:
              only:
                - /release\/.*/
                - master
                - drift
          requires:
            - build_docker_image
